version: '3.5'

services:
  psql:
    image: postgres
    ports:
      - 6543:5432
    environment:
      POSTGRES_PASSWORD: postgres

  mongodb:
    image: mongo
    command: mongod --replSet rs0
    ports:
      - 37017:27017
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  identity:
    image: notescribapi-identity
    build:
      context: src
      dockerfile: Services/Identity/Notescrib.Identity.Api/Dockerfile
    ports:
      - 50001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - psql

  notes:
    image: notescribapi-notes
    build:
      context: src
      dockerfile: Services/Notes/Notescrib.Notes.Api/Dockerfile
    ports:
      - 50002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mongodb

  emails:
    image: notescribapi-emails
    build:
      context: src
      dockerfile: Services/Emails/Notescrib.Emails.Api/Dockerfile
    ports:
      - 50003:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - EmailSettings__From=''
      - EmailSettings__Password=''

  apigateway:
    image: notescribapi-apigateway
    build:
      context: src
      dockerfile: Notescrib.ApiGateway/Dockerfile
    ports:
      - 50000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

networks:
  default:
    name: notescrib_network
    driver: bridge
