version: '3.5'

services:
  psql:
    image: postgres
    ports:
      - 6543:5432
    environment:
      POSTGRES_PASSWORD: postgres
  
  identity:
    image: notescrib-identity
    build:
      context: src
      dockerfile: Notescrib.Identity.Api/Dockerfile
    ports:
      - 50001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - EmailSettings__From=
      - EmailSettings__Password=
    depends_on:
      - psql

  notes:
    image: notescrib-notes
    build:
      context: src
      dockerfile: Notescrib.WebApi/Dockerfile
    ports:
      - 50000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - mongodb

networks:
  default:
    name: notescrib_network
    driver: bridge
